encoding: utf-8
markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: 方治乾的博客
subTitle: 方治乾的个人博客
description: 方治乾的博客
url: http://fangzhiqian.github.io
feed: /atom.xml

#菜单配置
nav:
  - text:   Home
    url: /index.html
    icon: icon-home
    class: home
  - text:  Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text:   About me
    url: /me.html
    icon: icon-envelope-alt
    class: none
  - text: Contact
    url: /contact.html
    icon: icon-heart
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: 方志乾
